@startuml

class ProfileSample {
    - dateTime: ZonedDateTime
    - constituentData: List<ProfileConstituentData>
}

class ProfileConstituentData {
    + data: List<Double>
    + param: String
    + unit: String
}

class CsvDepthTempProfileSampleMeasurement {
    - delegate: DepthTempProfileSampleMeasurement
    //Used for csv serialization
}

ProfileSample"1" --> "n"ProfileConstituentData
CsvDepthTempProfileSampleMeasurement "1"--> "1" DepthTempProfileSampleMeasurement : composition

@enduml





